<%@ Page Title="Department" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Department.aspx.cs" Inherits="BerkleyCMS.WebForm2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <div>
        <h3>Department Details</h3>
    </div>
    <div>
        <div>
            <asp:Label ID="Label1" runat="server" Text="ID" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="idTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label2" runat="server" Text="Name" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="nameTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label3" runat="server" Text="Head of Department" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="hodTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
    </div>
            <asp:Button ID="btnSubmit" runat="server" OnClick="Button1_Click1" Text="Submit" CssClass="btn-primary" Font-Names="roboto" />

    <p>
        <asp:TextBox ID="IDStore" runat="server" Visible="False"></asp:TextBox>
        <br />

        <p>
            <asp:GridView ID="departmentGridView" runat="server" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" CellSpacing="10" Font-Names="roboto" Width="100%">
            </asp:GridView>
        </p>
    <p>
        &nbsp;</p>


</asp:Content>
