<%@ Page Title="Module" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Module.aspx.cs" Inherits="BerkleyCMS.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <div>
        <h3>Module Details</h3>
    </div>
    <div>
        <div>
            <asp:Label ID="Label1" runat="server" Text="Module Code" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="modTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label2" runat="server" Text="Module Name" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="nameTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label3" runat="server" Text="Credit Hours" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="chTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label4" runat="server" Text="Module Leader" Font-Names="roboto"></asp:Label>
            <asp:TextBox ID="modLeaderTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
  
    <p>
        <asp:TextBox ID="IDStore" runat="server" Visible="False"></asp:TextBox>
        <asp:Button ID="btnSubmit" runat="server" OnClick="Button1_Click1" Text="Submit" CssClass="bg-primary" Font-Names="roboto" />
        <br />

        <p>
            <asp:GridView ID="modGridView" runat="server" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" Height="139px" Width="100%" class="table table-bordered table-condensed table-responsive table-hover " CellSpacing="10" CssClass="container" Font-Bold="False" Font-Names="roboto" HorizontalAlign="Justify">
            </asp:GridView>
        </p>
    <p>
        &nbsp;</p>
        </div>
</asp:Content>
