<%@ Page Title="Teacher" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Teacher.aspx.cs" Inherits="BerkleyCMS.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h3>Teacher Details</h3>
    </div>
    <div>
        <div>
            <asp:Label ID="Label1" runat="server" Text="ID" Font-Names="roboto"></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="idTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label2" runat="server" Text="Name" Font-Names="roboto"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
            <asp:TextBox ID="nameTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label7" runat="server" Text="Teacher Email" Font-Names="roboto"></asp:Label>
            &nbsp;&nbsp;
            <asp:TextBox ID="emailTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
            <asp:Label ID="Label4" runat="server" Text="Date of Birth" Font-Names="roboto"></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="dobTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label5" runat="server" Text="Age" Font-Names="roboto"></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="ageTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label6" runat="server" Text="Designation" Font-Names="roboto"></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="desTxt" runat="server" CssClass="form-control" Font-Names="roboto"></asp:TextBox>
            <br />
        </div>
    </div>
    <asp:Button ID="btnSubmit" runat="server" OnClick="Button1_Click1" Text="Submit" CssClass="btn-primary" Font-Names="roboto" />
    <p>
        <asp:TextBox ID="IDStore" runat="server" Visible="False"></asp:TextBox>
        <p>
        
        <br />

            <asp:GridView ID="teacherGridView" runat="server" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" Height="139px" Width="100%"
            class="table table-bordered table-condensed table-responsive table-hover " CellSpacing="10" CssClass="container-fluid" Font-Names="roboto" HorizontalAlign="Center">
            
            </asp:GridView>
    <p>
        &nbsp;</p>

</asp:Content>
